server:
  port: ${PORT:8761}

eureka:
  instance:
    hostname: ${RAILWAY_STATIC_URL:localhost}
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info
  client:
    register-with-eureka: false
    fetch-registry: false
